parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: imageType
    displayName: 'Select Image Type for the agent'
    type: string
    default: ubuntu2204
    values:
      - windows2022
      - ubuntu2204
      - windows2019
      - ubuntu2004

pr:
  branches:
    include:
    - main
  paths:
    include:
    - infra/build-agent/*

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
    - infra/build-agent/*

resources:
  repositories:
    - repository: ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA-ADP
      type: github
      ref: main

variables:
  imageType: ${{ parameters.imageType }}
  ${{ if eq(parameters.imageType, 'ubuntu2204') }}:
    instanceNumber: 01
  ${{ if eq(parameters.imageType, 'windows2022') }}:
    instanceNumber: 02
  ${{ if eq(parameters.imageType, 'windows2019') }}:
    instanceNumber: 03
  ${{ if eq(parameters.imageType, 'ubuntu2004') }}:
    instanceNumber: 04

extends:
  template: /pipelines/common-infra-deploy.yaml@ADPPipelineCommon
  parameters:
    projectName: $(projectName)
    deployFromFeature: ${{ parameters.deployFromFeature }}
    environments:
      - name: 'snd4'
        serviceConnection: AZR-ADP-SND4
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'
      - name: 'dev1'
        serviceConnection: AZR-ADP-DEV1
        dependsOn: 'snd4'
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'
      - name: 'tst1'
        serviceConnection: AZR-ADP-TST1
        dependsOn: 'dev1'
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'
      - name: 'pre1'
        serviceConnection: AZR-ADP-PRE1
        dependsOn: 'tst1'
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'
      - name: 'prd1'
        serviceConnection: AZR-ADP-PRD1
        dependsOn: 'pre1'
        deploymentBranches:
          - 'refs/heads/main'
        azureRegions:
          primary: 'UKSouth'
    groupedDeployments:
      - name: build_agent
        deployments:
        - name: Deploy Build Agent - ${{ parameters.imageType }}
          type: 'script'
          scriptType: AzureCLI
          azureCLIScriptType: pscore
          path: infra/build-agent/Create-AdoBuildAgent.ps1
          scriptArguments: > 
            -ImageGalleryTenantId $(imageGalleryTenant)
            -TenantId $(tenantId)
            -SubscriptionName $(subscriptionName)
            -ResourceGroup $(servicesResourceGroup)
            -VMSSName $(infraResourceNamePrefix)$(nc_resource_virtualmachine_scalesets)$(nc_instance_regionid)$(instanceNumber)
            -SubnetId /subscriptions/$(subscriptionId)/resourceGroups/$(virtualNetworkResourceGroup)/providers/Microsoft.Network/virtualNetworks/$(virtualNetworkName)/subnets/$(networkResourceNamePrefix)$(nc_resource_subnet)$(nc_instance_regionid)99
            -ImageId /subscriptions/$(imageGallerySubscription)/resourceGroups/$(imageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/$(imageGalleryName)/images/${{ parameters.imageType }}
            -KeyVaultName $(ssvPlatformKeyVaultName)
            -Location $(location)
            -SecretsPrefix $(environment)$(nc_instance_regionid)-$(instanceNumber)
